### PR TITLE
dump_joints_robot.m file does not exists

### PR DESCRIPTION
**Pull request by traversaro**
Perhaps it was referring to the `dump_joints.m` file? 

cc @rbonghi Furthermore, in the README section "Other information and OLD information" which information is "other" and which one is "OLD"?

### CODE REVIEW

**Comment by rbonghi** [comment]
Yes, `dump_joint.m` is correct. Thank you!
I do not update the readme.m, in the last days.

Second question I split in two categories:
- **Other information**
  We have list of files with you can update the list of joints, an example this list of path in readme.

> In `scripts` folder you have other script to compare or analyze information about joint or single data.
> `codyco-superbuild/src/modules/wholeBodyDynamicsTree/app/robots/`**NAME_ROBOT**`/wholeBodyDynamicsTree.ini`
> - In `codyco-superbuild/libraries/yarpWholeBodyInterface/app/robots/`**NAME_ROBOT**`/yarpWholeBodyInterface.ini`
>   Under **[WBI_ID_LISTS]** add:
> 
> ```
> JOINT_FRICTION = (NAME_JOINT)
> ```
> 
> example:
> 
> ```
> JOINT_FRICTION = (l_hip_pitch)
> ```
> 
> Quickly way: `codyco-superbuild/build/install/share/codyco/robots/`**NAME_ROBOT**`/yarpWholeBodyInterface.ini`
- **Old information**
  The old way without script in matlab for update joint list. The last part of readme.m

**Comment by traversaro** [comment]
We can get rid of old information ?

**Comment by rbonghi** [comment]
Yes, I think to open a wiki page in this repo with old information.

It is a quickly reminder for me to find all information in codyco

**Comment by traversaro** [comment]
:+1:

**Comment by rbonghi** [comment]
I Added on wiki this page:
https://github.com/rbonghi/FrictionJoint/wiki/How-to-find-file-configuration-in-codyco

I can start to remove all futile information in readme.m

**Comment by rbonghi** [comment]
Updated readme.m with last commit d1fbe421840a769857e58ac1a04e848d8f02c919

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
