### PR TITLE
[doc] add instructions for performing estimation

### PR DESCRIPTION
**Pull request by traversaro**
for friction in a joint actuated by a single motor.

cc @hu-yue @DanielePucci @randaz81

### CODE REVIEW

**Comment by traversaro** [comment]
Anyone willing to do the same for coupled joints, to avoid misunderstandings ? cc @DanielePucci @rbonghi

**Comment by rbonghi** [comment]
Yes, the procedure is the same compare to single joint, but you can change the method in `dump_joints.m` and set in idle three joints.

**Comment by traversaro** [comment]
Added instructions for coupled joints.

**Comment by rbonghi** [comment]
Thank you! @traversaro

**Pull request merged**
